### ISSUE TITLE
UI Redesign Home Page

### ISSUE THREAD

**Issue by GreyActOwl1** [GreyActOwl1/AlfredAI#8]
**Description:**
- Redesign the home page based on the mockups.
- Implement a dark mode option that users can toggle.
- Ensure all elements are consistent with the other pages on the site .

**Notes:**
- Refer to the attached Figma images for guidance on layout and styling.
- Ensure that the dark mode has proper contrast and readability.

**Mockups:**
![AlfredAI-HomePage-Light](https://github.com/user-attachments/assets/e63b78c3-ac46-4c0d-907f-3bdbdd53ce58)

from [Figma Project](https://www.figma.com/design/Hfc7Wk1v1Ddw9EcSfc9MJb/Project-3---Alfred-AI?node-id=0-1&t=qSOQVO6pojaKfKKh-1)

**Comment by M-Umar-Amir** [comment]
I added dark mode, and improved design. The changes are made and can be seen on Figma designs.

**Comment by GreyActOwl1** [comment]
#11 Adds the redesign. Closing as Complete.
