### ISSUE TITLE
Add Feature for Multiple Chats

### ISSUE THREAD

**Issue by jballo** [GreyActOwl1/AlfredAI#9]
Description:
We need to implement a feature that allows users to have multiple chat sessions simultaneously. This will enhance user experience by enabling them to switch between different conversations easily without losing context.

Acceptance Criteria:

1. Users can initiate multiple chat sessions.
2. Users can switch between different chat sessions without losing the conversation history.
3. Each chat session is maintained separately with its own conversation history.
4. Users can add and remove chat sessions as needed.
5. Interface should be intuitive and easy to navigate between different chat sessions.

**Comment by GreyActOwl1** [comment]
#10 implements the feature allowing users to have multiple chat sessions simultaneously. To fully apply the fix for issue #13, a redeployment may be required.
